#include<iostream>
using namespace std ;
int main(int argc, char const *argv[])
{
    
    int s = 's';
    int u = 'u';
    int r = 'r';
    int a = 'a';
    int j = 'j';
    cout<<"my name in SMALL ASCII formate:"<<s<<u<<r<<a<<j<<endl;
    int S = 'S';
    int U = 'U';
    int R = 'R';
    int A = 'A';
    int J = 'J';
    cout<<"my name in CAPITAL ASCII formate:"<<S<<U<<R<<A<<J;
   
    return 0;
}